---
title: "Installing Pyomo"
---

Pyomo is a Python wrapper around various solvers written in other languages. As such, you install Pyomo along with a solver to use it. In this course, we will use the open-source HiGHS solver from the University of Edinburgh.

Often, students end up with multiple Python installations on their computer, which can lead to confusion. The easiest way to avoid this is to use [Miniconda](https://docs.anaconda.com/miniconda/miniconda-install/) or [Anaconda](https://www.anaconda.com/) to manage your Python installation. If you already have Python installed, you can try installing Pyomo and HiGHS using `pip`, but if you run into issues, I recommend uninstalling your existing Python installation(s) and installing Miniconda instead.

(For those of you who are more experienced programmers, I recommend looking at [uv](https://github.com/astral-sh/uv) as an extremely fast and effective Python package manager. Though it requires some comfort with the command line.)

## Installation via Conda (existing install)

If you have installed Python via [Miniconda](https://docs.anaconda.com/miniconda/miniconda-install/) or [Anaconda](https://www.anaconda.com/), then you can install the required packages directly with `conda`.

From a terminal (Windows start menu → Terminal), run

```bash
conda install -c conda-forge pyomo highs
```

To install Pyomo and the HiGHS solvers. If the command is not found, you might need to run this command from an Anaconda command line (it might be an option on your start menu).

## Installation via Conda (new install)

Download and install [Miniconda](https://docs.anaconda.com/miniconda/miniconda-install/). Since this is a new installation, you will need to install various packages. I recommend running the following from a terminal (Windows start menu → Terminal) to install common packages:

```bash
conda install -c conda-forge scipy numpy matplotlib ipython pyomo highs
```

If the command is not found, it means that `conda` is not on your system path (i.e., the list of folders that Windows searches for programs to run). If you installed Miniconda in the default place, you should be able to change to the installation folder and run the command from there:

```bash
cd \Users\Your Username\AppData\Local\miniconda3\Scripts
conda install -c conda-forge scipy numpy matplotlib ipython pyomo highs
```

or (on some installs)

```bash
cd \Users\Your Username\miniconda3\Scripts
conda install -c conda-forge scipy numpy matplotlib ipython pyomo highs
```

If you use PyCharm, Spyder, or VS Code, you will need to change the Python interpreter they use to the new one.

- [PyCharm instructions](https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html)
- [Spyder instructions](https://docs.spyder-ide.org/current/faq.html) - see "How do I get Spyder to work with my existing Python packages/environment"
- [VS Code instructions](https://code.visualstudio.com/docs/python/environments)

## Installing via Pip

If you can install Pyomo and HiGHS using `pip`:

```bash
pip install pyomo highspy
```

If you have installed Python using Anaconda (or Miniconda), it is recommended to use `conda` instead of `pip` to avoid conflicts between packages.

## Using Google Colab

If you have a Google account, you have free access to [Colab](https://colab.research.google.com/). This provides a notebook-style interface to cloud-based computers with Python already installed. Simply create a new notebook in Colab and add these lines to the top of the notebook:

```bash
!pip install pyomo highspy
```

These commands need to be run each time you re-open the notebook, but they only need to be run once per session. As such, it is best to keep them in a cell that is separate from the rest of your work at the top of the notebook.

HiGHS also has an [example notebook on Google Colab](https://colab.research.google.com/drive/1JmHF53OYfU-0Sp9bzLw-D2TQyRABSjHb?usp=sharing).
